### ISSUE TITLE
Launch Pad 2 has too little friction

### ISSUE THREAD

**Issue by tfischer4765** [taniwha-qf/Extraplanetary-Launchpads#102]
After deployment, the launchpad can easily slide around, one even can activate the engine and move it around on its own power. That shouldn't be possible, the part should have a very high friction when deployed. Putting something underneath is not a good option because then the launchpad isn't properly set on the ground any more.

KAS has an anchor that apparently uses enhanced friction, the Utilitron Grasper from the infernal robotics rework utility pack uses the KAS grapling hook module for the purpose. Maybe some of that is reusable.

**Comment by taniwha-qf** [comment]
Actually, launchpad2 is a mess of inter-penetrating colliders which causes all sorts of physics grief. f1ae97c should improve things.
