### ISSUE TITLE
Launchpad won't build

### ISSUE THREAD

**Issue by TraindKilla** [taniwha-qf/Extraplanetary-Launchpads#84]
I can access the launchpad UI but the build percentage won't move. I have a self-sufficient launchpad on Minmus that i was able to build on before, and suddenly i am unable to build from it. I have several Kerbals in a workshop connected to the launchpad and 20K+ rocket parts to work with. I am stumped! It was working so well before; i don't know what happened.

**Comment by TraindKilla** [comment]
I was playing around with my Minmus base the other day, and once again it would not build.  Determined to figure this out, I'm now sure I know why.  

So, I decided that I was just going to rebuild my base on Minmus from the ground up to see if that would fix the problem. I evacuated one of my Kerbals from the workshop and proceeded to disconnect the various modules of my base (I had them connected together using KAS parts, which seem to work well).  Once I had disconnected all of the modules, I then returned the Kerbal to the workshop.  When inside, I noticed that I left something building and that the percentage had slightly gone up, however, the craft stopped building again.  Then it hit me.  Could it be that one of my Kerbals was so stupid that he was doing more harm than good?  It was true; the Kerbal I was using to do all the labor on my base was so stupid that my base would stop building when he got inside.  LOL!  What an awesome feature to include in the EL mod.  I will be more aware of the way I place my Kerbals from now on.

This issue can now be closed due to user error. :stuck_out_tongue_closed_eyes: 

Is there a way to view your Kerbal's attributes when not at KSC?

**Comment by henrybauer** [comment]
>Is there a way to view your Kerbal's attributes when not at KSC?

In map view, on the right-hand side there should be two buttons, one to view the current vessel's stats, and one to view the Kerbal's stats.

To be clear, you can view a Kerbal's attributes in KSC even if they're already in space; just click on the "Assigned" tab.

**Comment by TraindKilla** [comment]
Thanks! I knew about the assigned tab, but never tried to use the info tab with Kerbals. That's sweet! My problem Kerbal is as stupid as they get! Lol

**Comment by TraindKilla** [comment]
Thanks! I knew about the assigned tab, but never tried to use the info tab with Kerbals. That's sweet! My problem Kerbal is as stupid as they get! Lol
