### ISSUE TITLE
Board/Evacuate Launchpad

### ISSUE THREAD

**Issue by TraindKilla** [taniwha-qf/Extraplanetary-Launchpads#85]
Is there a way to board or evacuate Kerbals from the launchpad? The only way i know to board the launchpad is to load them in at the VAB? Am i missing something? Is there another way?

**Comment by taniwha-qf** [comment]
CrewManifest might be of use for evacuating. Boarding can be done via the new transfer feature.

My current recommendation is to not use the part in the first place. The only reason I haven't deprecated it is there isn't much choice of pads, though using a combination of survey stakes and the orbital dock can go a long way to doing so.

I do have some thoughts to try for making launchpad2 not a hunk of junk, but for the meantime, either accept that it is a prison.

**Comment by taniwha-qf** [comment]
Partially fixed in 5.1.90.
