### ISSUE TITLE
EPL doesn't uses RPs

### ISSUE THREAD

**Issue by koshboo** [taniwha-qf/Extraplanetary-Launchpads#90]
the problem i am having is that EPL does not remove rocet part when building a ship. The epl display shows that is is but on the resource display they are not going down and if i switch to another ship and back the epl display shows the full tanks again.i am using the latest epl and mks/oks although is seem to be a EPL problem. There are no errors in the debug log
![screenshot1](https://cloud.githubusercontent.com/assets/7230072/5607823/c2f838ba-9463-11e4-86e1-f31b9d00d5cb.png)

**Comment by TraindKilla** [comment]
Sounds to me like you are creating rocket parts faster than you are using them. Do you have the drill extracting ore, the smelter creating metal, and the workshop creating rocket parts at the same time you are building?

**Comment by koshboo** [comment]
no this ship and the space station are being supplied via a logi hub atm

**Comment by koshboo** [comment]
after doing some testing it seem like this is a broken save file problem.
