### ISSUE TITLE
Yet another KIS interaction problem - container cost calculation

### ISSUE THREAD

**Issue by progfz** [taniwha-qf/Extraplanetary-Launchpads#94]
Cost for items in Kerbal Inventory System containers is calculated in a wrong way and any resource could be made from rocket parts.

Steps to reproduce:
- install KIS and EPL
- make new ship in VAB/SPH
- add KIS container
- put any small tank with fuel into KIS container
- look at EPL cost - there is no optional fuel cost there and rocket parts cost is enormous high
- remove tank from container and add it directly
- look at EPL cost - there is optional fuel cost and rocket parts cost is much smaller

**Comment by taniwha-qf** [comment]
Should be fixed in 5.1.90.
